name: build-apk

on:
  push:
    tags:
      - 'v*'
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # 不要再 apt 装 gradle！apt 版本太老
      - name: Bootstrap Gradle 8.7 and generate wrapper
        run: |
          GRADLE_VERSION=8.7
          wget -q https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
          unzip -q gradle-${GRADLE_VERSION}-bin.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-${GRADLE_VERSION}/bin" >> $GITHUB_PATH
          gradle --version
          gradle wrapper --gradle-version ${GRADLE_VERSION}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Fetch libxposed api (api:100) and publish to mavenLocal
        run: |
          mkdir -p external
          git clone --depth=1 https://github.com/libxposed/api.git external/libxposed-api
          ./gradlew -p external/libxposed-api publishToMavenLocal

      - name: Build Release APK
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiFitnessAmapNavFix-APK
          path: app/build/outputs/apk/release/app-release.apk
